version: "3"
services:
  mongo:
    container_name: mongo
    volumes:
      - ./data:/data/db
    user: "1000:1000"
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - overlay
  app:
    container_name: docker-chat-app
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - mongo
    networks:
      - overlay
  client:
    container_name: docker-chat-app-client
    build: .
    volumes:
      - ./src/client:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - app
    networks:
      - overlay
networks:
  overlay:
